Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Excludes:
    - db/**/*
    - config/**/*
    - script/**
    - bin/**
    - spec/**/*
    - vendor/**/*
    - app/controllers/users/*
Metrics/MethodLength:
  Max: 15
Metrics/ClassLength:
  Max: 102
Lint/MissingSuper:
  Exclude:
    - 'app/controllers/api/*'
